# k8s/ai-agent-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-secret
  namespace: traceassist
type: Opaque
stringData:
  OPENAI_API_KEY: "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"
  
